### ISSUE TITLE
Could not pass ClientConnectionEvent$Join$Impl

### ISSUE THREAD

**Issue by JuanL23** [Ve6om/WelcomeTitles#1]
**### Environment**

    Sponge Version: spongeforge-1.12.2-2705-7.1.0-beta-3126

    Plugin Version: WelcomeTitles-2.0.0.jar

    Forge Version: forge-1.12.2-14.23.4.2705-universal.jar

### **What happens?**

Hello,

Every time when a user log-in to the server I had a error message in the server-terminal (see the error stack below please).

Have a nice day.

### **More information**

[18:45:57] [Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Join$Impl to Plugin{id=welcometitles, name=WelcomeTitles, version=2.0.0, description=Custom titles for when players join., authors=[Ve6om], source=/opt/minecraft/mods/plugins/WelcomeTitles-2.0.0.jar}
java.lang.IncompatibleClassChangeError: Found interface org.spongepowered.api.text.title.Title$Builder, but class was expected
        at io.github.Ve6om.WelcomeTitles.onJoin(WelcomeTitles.java:87) ~[WelcomeTitles.class:?]
        at org.spongepowered.common.event.listener.JoinListener_WelcomeTitles_onJoin21.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2705-8.0.0-BETA-3474]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3474]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:347) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3474]
        at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:435) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3474]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-8.0.0-BETA-3474]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:445) [SpongeEventManager.class:1.12.2-2705-8.0.0-BETA-3474]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:1.12.2-2705-8.0.0-BETA-3474]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1677) [pl.class:?]
        at shadows.fastbench.net.HijackedDedicatedPlayerList.initializeConnectionToPlayer(HijackedDedicatedPlayerList.java:19) [HijackedDedicatedPlayerList.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285) [gw.class:?]
        at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180) [oz.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252-ea]

**Comment by Ve6om** [comment]
Hey there! Please ensure that you have the correct dependencies, and that you're running the latest SpongeForge stable build.

**Dependencies:**
[Luckperms](https://luckperms.net/)
[PlaceholderAPI](https://ore.spongepowered.org/rojo8399/PlaceholderAPI)

**Latest Sponge Build:**
**1.12.2-2838-7.2.0**
[Page](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2)

**Comment by Ve6om** [comment]
I'm closing this issue. Please reopen it if this continues.
